version: 2.9

builds:
  - binary: claude-squad
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
  draft: true
  replace_existing_draft: true

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github

  filters:
    exclude:
      - "^docs:"
      - typo
      - "^refactor"
      - "^chore"

brews:
  -
    name: claude-squad
    url_template: "https://github.com/smtg-ai/claude-squad/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://smtg-ai.github.io/claude-squad/"
    description: "Manage multiple AI agents like Claude Code, Aider, and more. 10x your productivity."
    license: "AGPL-3.0"
    skip_upload: false
    dependencies:
      - name: tmux
      - name: gh
        type: optional
    test: |
      system "#{bin}/cs version"
    repository:
      owner: smtg-ai
      name: homebrew-claude-squad
      branch: brew-tap
      token: "{{ .Env.HOMEBREW_REPO_TOKEN }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: smtg-ai
          name: homebrew-claude-squad
          branch: main